name: Amk çalış artık

on:
  schedule:
    - cron: "0 */6 * * *"  # Her 6 saatte bir çalışır
  workflow_dispatch:       # Manuel çalıştırma desteği

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo klonla
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Gerekli kütüphaneleri yükle
        run: pip install requests

      - name: M3U dosyasını oluştur
        run: python generate_m3u.py

      - name: Değişiklikleri push et
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "AutoUpdater"
          git config --global user.email "auto@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add .
          git commit -m "🔄 Otomatik M3U güncellemesi" || echo "Değişiklik yok"
          git push origin HEAD:main
