name: Günlük M3U Güncellemesi

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repositories klonlanıyor
      uses: actions/checkout@v3

    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Gerekli kütüphaneler yükleniyor
      run: pip install requests

    - name: M3U dosyası oluşturuluyor
      run: python generate_m3u.py

    - name: Değişiklikleri commit et ve pushla
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "🔄 Otomatik M3U güncellemesi"
        git push
