name: M3U Otomatik Güncelleme

on:
  schedule:
    - cron: "0 */6 * * *"  # Her 6 saatte bir
  workflow_dispatch:       # Manuel çalıştırma

permissions:
  contents: write  # Botun repo içine push atabilmesi için GEREKLİ

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo klonla
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Gerekli kütüphaneleri yükle
        run: pip install requests

      - name: M3U dosyasını oluştur
        run: python generate_m3u.py

      - name: Değişiklikleri push et
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "🔄 Otomatik M3U güncellemesi" || echo "Değişiklik yok"
          git push origin HEAD:main
